INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');
/*Poblando VEHICULOS*/
INSERT INTO VEHICULOS (MARCA, MODELO, YEAR_VEHICLE)VALUES('Toyota','PRIUS','1997');
INSERT INTO VEHICULOS (MARCA, MODELO, YEAR_VEHICLE)VALUES('Toyota','SUPRA','1978');
INSERT INTO VEHICULOS (MARCA, MODELO, YEAR_VEHICLE)VALUES('Toyota','CROWN','1955');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Econoline E350', '2000');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'F150', '1975');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Aston Martin', 'DBS', '2008');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Escort', '1993');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', '2500 Club Coupe', '1997');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Durango', '1999');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Neon', '2001');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', 'X3', '2011');
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', '745', 2002);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Nissan', 'Maxima', 1997);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Cadillac', 'STS-V', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Jeep', 'Wrangler', 1994);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Traverse', 2012);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'E150', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mazda', 'MX-6', 1993);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'F-Series', 1991);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mitsubishi', 'Eclipse', 2001);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Studebaker', 'Avanti', 1963);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mazda', 'Miata MX-5', 1996);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', '760', 2003);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Sierra 3500', 2002);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mercedes-Benz', 'S-Class', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Pontiac', 'Daewoo Kalos', 2005);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Acura', 'Legend', 1992);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Volkswagen', 'GTI', 1987);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Vandura 3500', 1994);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Toyota', 'Camry', 1992);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Pontiac', 'Firebird', 1995);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Toyota', 'Avalon', 2000);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Suzuki', 'Forenza', 2004);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Fiesta', 2011);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Silverado', 2003);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mitsubishi', 'Challenger', 1997);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Bentley', 'Continental GT', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Suburban 2500', 2012);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Toyota', 'Tundra', 2008);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Kia', 'Amanti', 2009);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Savana', 2011);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chrysler', 'Cirrus', 1999);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Explorer', 1994);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mazda', 'Millenia', 1996);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lincoln', 'Continental', 1992);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lamborghini', 'Gallardo', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Audi', 'A5', 2011);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', 'M5', 2003);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'F250', 2008);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Eagle', 'Talon', 1992);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Maybach', 'Landaulet', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Nissan', 'Pathfinder', 2008);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Infiniti', 'FX', 2004);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mercury', 'Grand Marquis', 1991);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Acura', 'RL', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Suzuki', 'Sidekick', 1991);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lamborghini', 'Murciélago', 2007);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Pontiac', 'GTO', 1971);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lincoln', 'LS', 2004);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Kia', 'Soul', 2012);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Avalanche', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Jaguar', 'S-Type', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chrysler', '300', 2005);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Taurus', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Plymouth', 'Laser', 1989);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Honda', 'Pilot', 2009);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Stealth', 1995);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', '5 Series', 1995);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Ram Van B150', 1994);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mercury', 'Mountaineer', 1999);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Pontiac', 'Firefly', 1990);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Corvette', 1988);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Jaguar', 'XF', 2012);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Ram 1500 Club', 1997);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lincoln', 'Town Car', 2002);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Ford', 'Bronco', 1991);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Tahoe', 2002);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Yukon XL 2500', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Subaru', 'Outback', 2004);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Volkswagen', 'Fox', 1989);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Safari', 2005);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Lexus', 'GS', 2010);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Subaru', 'Alcyone SVX', 1997);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chevrolet', 'Blazer', 1999);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Volvo', '740', 1992);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('BMW', 'M3', 2001);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Nissan', 'Altima', 2006);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Dodge', 'Ram', 2009);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Mitsubishi', 'Endeavor', 2007);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('Chrysler', 'LHS', 2001);
insert into VEHICULOS (MARCA, MODELO, YEAR_VEHICLE) values ('GMC', 'Sierra Hybrid', 2006);

